[package]
authors     = { workspace = true }
description = "t3rn portal"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "pallet-portal-rpc"
readme      = { workspace = true }
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec     = { workspace = true, package = "parity-scale-codec" }
jsonrpsee = { workspace = true, features = [ "client-core", "server", "macros" ] }

pallet-portal-rpc-runtime-api = { path = "runtime-api" }
sp-api                        = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0' }
sp-std                        = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0' }
sp-blockchain                 = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0' }
sp-core                       = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0' }
sp-rpc                        = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0' }
sp-runtime                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0' }
t3rn-types                    = { path = "../../../types" }
