# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

# Grouppings are used to group together dependencies that should be updated
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
groups:
  dev-dependencies:
    patterns:
    - "*" # match all packages in single ecosystem
    update-types:
    - "minor"
    - "patch"

registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.GH_PAT}}

updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 2
    schedule:
      interval: weekly

  # Rust
  - package-ecosystem: cargo
    directory: /
    registries:
      - github
    open-pull-requests-limit: 2
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: client/packages/executor
    open-pull-requests-limit: 1
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-patch]

  # TODO: uncomment when we have a proper tests for all node applications

  # - package-ecosystem: npm
  #   directory: client/packages/cli
  #   open-pull-requests-limit: 1
  #   schedule:
  #     interval: daily
  #   ignore:
  #     - dependency-name: "*"
  #       update-types: [version-update:semver-patch]

  # - package-ecosystem: "npm" 
  #   directory: "client/packages/sdk"
  #   schedule:
  #     interval: "daily"

  # - package-ecosystem: "npm" 
  #   directory: "client/packages/types"
  #   schedule:
  #     interval: "daily"
