# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"

  # Rust
  - package-ecosystem: "cargo" 
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/primitives"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/node/t0rn-parachain"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/runtime/t0rn-parachain"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/node/standalone"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/types"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/types/abi"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/finality-verifiers/grandpa"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  - package-ecosystem: "cargo" 
    directory: "/finality-verifiers/common"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  # TODO: uncomment when we have a proper tests for all node applications
  # - package-ecosystem: "npm" 
  #   directory: "client/packages/cli"
  #   schedule:
  #     interval: "daily"

  - package-ecosystem: "npm" 
    directory: "client/packages/executor"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"

  # - package-ecosystem: "npm" 
  #   directory: "client/packages/sdk"
  #   schedule:
  #     interval: "daily"

  # - package-ecosystem: "npm" 
  #   directory: "client/packages/types"
  #   schedule:
  #     interval: "daily"
