[package]
authors = [ "Snowfork <contact@snowfork.com>" ]
edition = "2018"
name    = "snowbridge-core"
version = "0.1.1"

[dependencies]
serde = { version = "1.0", optional = true, features = [ "derive" ] }
#codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false, features = [ "derive" ] }

ethereum-types = { version = "0.12.1", default-features = false, features = [ "codec", "rlp", "serialize" ] }

scale-info = { version = "1.0", default-features = false, features = [ "derive" ] }

enum-iterator       = "0.6.0"
snowbridge-ethereum = { path = "../ethereum", default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17", default-features = false }
frame-system  = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17", default-features = false }
sp-core       = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17", default-features = false }
sp-runtime    = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17", default-features = false }
sp-std        = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.17", default-features = false }

[dev-dependencies]
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }

[features]
default            = [ "std" ]
runtime-benchmarks = [  ]
std                = [ "serde/std", "codec/std", "scale-info/std", "ethereum-types/std", "frame-support/std", "sp-std/std", "sp-core/std", "sp-runtime/std", "snowbridge-ethereum/std" ]
