[package]
edition = "2021"
license = "Apache-2.0"
name    = "vacuum-precompile"
version = "1.5.0-rc.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false }

sp-std = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0', default-features = false }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
frame-system  = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
pallet-assets = { workspace = true }

fp-evm        = { path = "../../primitives", default-features = false }
pallet-evm    = { path = "../..", default-features = false }

precompile-util-solidity  = { path = "../util/solidity", default-features = false }
t3rn-primitives           = { default-features = false, path = "../../../../primitives" }

[dev-dependencies]
pallet-evm             = { path = "../.." }
rlp                    = { version = "0.5" }
t3rn-mini-mock-runtime = { path = "../../../../runtime/mini-mock" }

[features]
default = [ "std" ]
std     = [
    "sp-std/std",
    "codec/std",
    "t3rn-primitives/std",
    "frame-support/std",
    "frame-system/std",
    "fp-evm/std",
    "pallet-evm/std"
]
