[package]
name = "escrow-contracts-wrapper"
version = "0.3.0"
authors = ["Maciej Baj <maciej@maciejbaj.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://t3rn.io"
repository = "https://github.com/t3rn/t3rn/"
description = "A crate wraps pallet-contracts with escrowed execution"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bitflags = "1.0"
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-support = { version = "2.0.0", default-features = false }
frame-system = { version = "2.0.0", default-features = false }
pallet-contracts = { version = "2.0.0", default-features = false }
pallet-contracts-primitives = { version = "2.0.0", default-features = false }
parity-wasm = { version = "0.41.0", default-features = false }
pwasm-utils = { version = "0.14.0", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-core = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-io = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-sandbox = { version = "0.8.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }
wat = { version = "1.0", optional = true, default-features = false }
gateway-escrow-engine = { package = "gateway-escrow-engine", version = '0.3.0', path = '../', default-features = false}

[dev-dependencies]
assert_matches = "1.3.0"
hex-literal = "0.3.1"
pallet-balances = { version = "2.0.0" }
pallet-timestamp = { version = "2.0.0" }
pallet-randomness-collective-flip = { version = "2.0.0" }
pretty_assertions = "0.6.1"
wat = "1.0"

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-io/std",
	"sp-std/std",
	"sp-sandbox/std",
	"frame-support/std",
	"frame-system/std",
	"parity-wasm/std",
	"pwasm-utils/std",
	"wasmi-validation/std",
	"pallet-contracts/std",
	"pallet-contracts-primitives/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"wat",
	# We are linking the wat crate which uses std and therefore brings with it the
	# std panic handler. Therefore we need to disable out own panic handlers. Mind that
	# we still override the std memory allocator.
	"sp-io/disable_panic_handler",
	"sp-io/disable_oom",
]
