[package]
authors = [ "t3rn Ltd." ]
edition = "2018"
license = "Apache-2.0"
name    = "pallet-runtime-gateway-rpc-runtime-api"
version = "0.1.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
bitflags = { version = "1" }
codec    = { package = "parity-scale-codec", version = "2", default-features = false, features = [ "derive" ] }
serde    = { version = "1", features = [ "derive" ], default-features = false, optional = true }

# Substrate Dependencies

sp-api     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8' }
sp-core    = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8' }
sp-std     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.8' }

[features]
default = [ "std" ]
std     = [ "sp-api/std", "sp-core/std", "codec/std", "sp-std/std", "sp-runtime/std", "serde/std" ]
