[package]
edition    = "2018"
homepage   = "https://t3rn.io"
license    = "Apache-2.0"
name       = "pallet-circuit-vacuum"
readme     = "README.md"
repository = "https://github.com/t3rn/t3rn/"
version    = "1.9.0-rc.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v1.0.0' }
frame-system  = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v1.0.0' }

codec      = { package = "parity-scale-codec", version = "3", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.1.1", default-features = false, features = [ "derive" ] }
serde      = { version = "1.0", default-features = false, optional = true, features = [ "derive" ] }

log = { version = "0.4", default-features = false }

sp-core               = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v1.0.0', default-features = false }
sp-runtime            = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v1.0.0' }
sp-std                = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v1.0.0' }

frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v1.0.0', optional = true }

t3rn-abi        = { path = "../../../types/abi", default-features = false }
t3rn-types      = { path = "../../../types", default-features = false, features = [ "runtime" ] }
t3rn-primitives = { path = "../../../primitives", default-features = false }

rlp = { version = "0.5.2", features = [ "derive" ], default-features = false  }

[dev-dependencies]
hex                    = "0.4.2"
hex-literal            = "0.2.1"
t3rn-mini-mock-runtime = { path = "../../../runtime/mini-mock" }


[features]
default = [ "std" ]
std = [
    "rlp/std",
    "serde",
    "codec/std",
    "scale-info/std",
    "log/std",
    "sp-core/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "t3rn-primitives/std",
    "t3rn-abi/std",
    "t3rn-types/std",
]

try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime", "t3rn-abi/std", "t3rn-types/std" ]

runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks", "frame-support/runtime-benchmarks", "frame-system/runtime-benchmarks", "sp-runtime/runtime-benchmarks" ]

test-skip-verification = [  ]
