[package]
authors     = [ "t3rn devs <team@t3rn.io" ]
description = "Implements t3rn x-chain executors staking."
edition     = "2021"
homepage    = "https://t3rn.io/"
license     = "Apache 2.0"
name        = "pallet-executors"
publish     = false
repository  = "https://github.com/t3rn/t3rn"
version     = "1.0.0-rc.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec              = { package = "parity-scale-codec", version = "3", default-features = false, features = [ "derive", "max-encoded-len" ] }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36", default-features = false }
frame-support      = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36", default-features = false }
frame-system       = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36", default-features = false }
log                = { version = "0.4", default-features = false }
scale-info         = { version = "2.1.1", default-features = false, features = [ "derive" ] }
serde              = { version = "1.0", default-features = false, features = [ "derive" ] }
sp-runtime         = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36", default-features = false }
sp-std             = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36", default-features = false }
t3rn-primitives    = { path = "../../primitives", default-features = false }

[dev-dependencies]
pallet-3vm                                 = { path = "../../3vm/pallets/3vm", default-features = false }
pallet-3vm-contracts                       = { path = "../../3vm/pallets/contracts", default-features = false, package = "pallet-contracts" }
pallet-3vm-contracts-primitives            = { path = "../../3vm/primitives/contracts", default-features = false, package = "pallet-contracts-primitives" }
pallet-3vm-contracts-rpc-runtime-api       = { path = "../../3vm/rpc/contracts/runtime-api", default-features = false, package = "pallet-contracts-rpc-runtime-api" }
pallet-account-manager                     = { path = "../account-manager", default-features = false }
pallet-balances                            = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }
pallet-clock                               = { path = "../clock", default-features = false }
pallet-timestamp                           = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.36', default-features = false }
pallet-transaction-payment                 = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
similar-asserts                            = "1.1.0"
sp-core                                    = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }
sp-io                                      = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.36" }

[features]
default = [ "std" ]
std = [
  "log/std",
  "serde/std",
  "codec/std",
  "scale-info/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-io/std",
  "pallet-balances/std",
  "pallet-3vm/std",
  "pallet-3vm-contracts/std",
  "pallet-3vm-contracts-primitives/std",
  "pallet-3vm-contracts-rpc-runtime-api/std",
  "pallet-clock/std",
  "pallet-account-manager/std",
  "pallet-transaction-payment/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-timestamp/std",
  "t3rn-primitives/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking/std",
]

runtime-benchmarks = [ "frame-benchmarking/runtime-benchmarks" ]
try-runtime        = [ "frame-support/try-runtime" ]
