[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "x-chain DNS"
edition     = "2018"
homepage    = "https://t3rn.io"
license     = "Apache 2.0"
name        = "pallet-xdns"
readme      = "README.md"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.0.0-alpha.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec      = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
log        = { version = "0.4.14", default-features = false }
scale-info = { version = "1.0", default-features = false, features = [ "derive" ] }
serde      = { version = "1.0", default-features = false, optional = true }

frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', optional = true }
frame-metadata     = { version = "14.0.0", features = [ "v13", "v14" ], default-features = false }
frame-support      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
frame-system       = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }

pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }

sp-io      = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-std     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
sp-version = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }

t3rn-primitives = { path = "../../primitives", default-features = false }
t3rn-protocol   = { path = "../../protocol", default-features = false }

[dev-dependencies]
sp-core     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }

pallet-balances           = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }
pallet-sudo               = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17' }

[features]
default = [ "std" ]
runtime-benchmarks = [ "frame-benchmarking" ]
std = [
  "codec/std",
  "frame-benchmarking/std",
  "frame-support/std",
  "frame-metadata/std",
  "frame-system/std",
  "log/std",
  "pallet-timestamp/std",
  "scale-info/std",
  "serde/std",
  "sp-io/std",
  "sp-version/std",
  "sp-runtime/std",
  "sp-std/std",
  "t3rn-primitives/std",
  "t3rn-protocol/std",
]
try-runtime = [ "frame-support/try-runtime" ]
