[package]
edition    = { workspace = true }
homepage   = { workspace = true }
license    = { workspace = true }
name       = "precompile-util"
repository = { workspace = true }
version    = { workspace = true }

[dependencies]
pallet-3vm-evm             = { path = "../..", default-features = false, package = "pallet-evm" }
pallet-3vm-evm-primitives  = { path = "../../primitives", default-features = false, package = "fp-evm" }
pallet-3vm-account-mapping = { path = "../../../3vm/account-mapping", default-features = false }
portal-precompile          = { path = "../portal", default-features = false }
tokens-precompile          = { path = "../tokens", default-features = false }

sp-core                   = { workspace = true }
sp-std                    = { workspace = true }
pallet-assets             = { workspace = true }

pallet-evm-precompile-3vm-dispatch = { path = "../3vm-dispatch", default-features = false }
pallet-evm-precompile-blake2       = { path = "../blake2", default-features = false }
pallet-evm-precompile-bn128        = { path = "../bn128", default-features = false }
pallet-evm-precompile-curve25519   = { path = "../curve25519", default-features = false }
pallet-evm-precompile-dispatch     = { path = "../dispatch", default-features = false }
pallet-evm-precompile-ed25519      = { path = "../ed25519", default-features = false }
pallet-evm-precompile-modexp       = { path = "../modexp", default-features = false }
pallet-evm-precompile-sha3fips     = { path = "../sha3fips", default-features = false }
pallet-evm-precompile-simple       = { path = "../simple", default-features = false }

[features]
default = [ "std" ]
std = [
  "sp-core/std",
  "sp-std/std",
  "pallet-3vm-evm-primitives/std",
  "pallet-3vm-evm/std",
  "portal-precompile/std",
  "tokens-precompile/std",
  "pallet-evm-precompile-3vm-dispatch/std",
  "pallet-evm-precompile-blake2/std",
  "pallet-evm-precompile-bn128/std",
  "pallet-evm-precompile-curve25519/std",
  "pallet-evm-precompile-dispatch/std",
  "pallet-evm-precompile-ed25519/std",
  "pallet-evm-precompile-modexp/std",
  "pallet-evm-precompile-sha3fips/std",
  "pallet-evm-precompile-simple/std",
]
