[package]
name = "relay-substrate-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
async-std = { version = "1.6.5", features = ["attributes"] }
async-trait = "0.1.40"
codec = { package = "parity-scale-codec", version = "2.2.0" }
jsonrpsee-proc-macros = "0.2"
jsonrpsee-types = "0.2"
jsonrpsee-ws-client = "0.2"
log = "0.4.11"
num-traits = "0.2"
rand = "0.7"
tokio = "1.8"

# Bridge dependencies

bp-header-chain = { path = "../../primitives/header-chain" }
bp-runtime = { path = "../../primitives/runtime" }
finality-relay = { git = "https://github.com/t3rn/parity-bridges-common", branch = "polkadot-v0.9.10-dev" }
headers-relay = { git = "https://github.com/t3rn/parity-bridges-common", branch = "polkadot-v0.9.10-dev" }
relay-utils = { git = "https://github.com/t3rn/parity-bridges-common", branch = "polkadot-v0.9.10-dev" }

# Substrate Dependencies

frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-storage = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }
sp-version = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.10" }

#[dev-dependencies]
futures = "0.3.7"
