apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fast-writer.fullname" . }}
  labels:
    {{- include "fast-writer.labels" . | nindent 4 }}
data:
  sideEffects: {{ .Values.sideEffects | toJson }}