
[package]
name = "pallet-multi-finality-verifier"
version = "1.0.0-alpha.0"
authors = ["t3rn ltd. <team@t3rn.io>"]
edition = "2018"
license = "Apache 2.0"
homepage = "https://t3rn.io"
repository = "https://github.com/t3rn/t3rn/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "2.2.0", default-features = false }
finality-grandpa = { version = "0.14.0", default-features = false }
log = { version = "0.4.14", default-features = false }
serde = { version = "1.0", optional = true }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

# Substrate Dependencies

frame-support = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
sp-trie = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false }
pallet-xdns = { path = "../xdns", default-features = false }
t3rn-primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
sp-io = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', default-features = false, features = ['std'] }
pallet-balances = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', features = ['std'] }
pallet-timestamp = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', features = ['std'] }
pallet-sudo = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.17', features = ['std'] }


[features]
default = ["std"]
std = [
	"codec/std",
	"finality-grandpa/std",
	"frame-support/std",
	"frame-system/std",
	"log/std",
	"serde",
	"sp-finality-grandpa/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-trie/std",
	"pallet-xdns/std",
	"t3rn-primitives/std"
]
runtime-benchmarks = []
