[package]
name        = "pallet-rewards"
edition     = "2018"
homepage    = "https://t3rn.io"
license     = "Apache-2.0"
readme      = "README.md"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.9.0-rc.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
frame-support      = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
frame-system       = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

scale-info       = { version = "2.7.0", default-features = false, features = [ "derive" ] }
serde            = { version = "1.0", default-features = false, optional = true, features = [ "derive" ] }
codec            = { package = "parity-scale-codec", version = "3", default-features = false, features = [ "derive" ] }

log              = { version = "0.4", default-features = false }

sp-core            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27', default-features = false}
sp-runtime         = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-std             = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-application-crypto = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27', optional = true }

t3rn-primitives = { path = "../../primitives", default-features = false }

[dev-dependencies]
hex                             = "0.4.2"
hex-literal                     = "0.4.1"
t3rn-mini-mock-runtime      = { path = "../../runtime/mini-mock" }

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "scale-info/std",
    "log/std",
    "sp-core/std",
    "sp-application-crypto/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "t3rn-primitives/std",
]

try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime" ]

runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks"
]
