[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "Primitives for a 3VM enabled EVM RPC."
edition     = "2021"
license     = "Apache-2.0"
name        = "pallet-evm-rpc-runtime-api"
repository  = "https://github.com/t3rn/3vm/"
version     = "0.1.0"

[dependencies]
ethereum       = { version = "0.14.0", default-features = false, features = [ "with-codec" ] }
ethereum-types = { version = "0.14.1", default-features = false }

codec      = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.7.0", default-features = false, features = [ "derive" ] }
sp-api     = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-core    = { version = "6.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-io      = { version = "6.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-runtime = { version = "6.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.27" }
sp-std     = { version = "4.0.0", git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.27" }

fp-evm = { version = "3.0.0-dev", path = "../../primitives", default-features = false }

[features]
default = [ "std" ]
std     = [ "ethereum/std", "ethereum-types/std", "codec/std", "scale-info/std", "sp-api/std", "sp-core/std", "sp-io/std", "sp-runtime/std", "sp-std/std", "fp-evm/std" ]
