[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "Node-specific RPC methods for interaction with evm contracts."
edition     = "2021"
license     = "Apache-2.0"
name        = "pallet-evm-rpc"
repository  = "https://github.com/t3rn/3vm/"
version     = "0.0.1"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec     = { package = "parity-scale-codec", version = "3.0.0" }
jsonrpsee = { version = "0.19.0", features = [ "server", "macros" ] }
serde     = { version = "1", features = [ "derive" ] }

# Substrate Dependencies
pallet-evm-primitives      = { path = "../primitives", package = "fp-evm" }
pallet-evm-rpc-runtime-api = { path = "runtime-api" }
sp-api                     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-blockchain              = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-core                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-rpc                     = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-runtime                 = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }

[dev-dependencies]
serde_json = "1"
