---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: t3rn-blockchain
    release: kube-prometheus-stack    
    app: kube-prometheus-stack
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
  name: executor.rules
  namespace: executor
spec:
  groups:
  - name: executor-bidding.rules
    rules:

    - alert: ExecutorNoWin
      annotations:
        description: Executor stopped winning bidding
        monitoring: https://monitoring.t3rn.io/d/0VXqnBj4k/executors?orgId=1&refresh=30s
      expr: increase(executor_bid_total{scenario="Won"}[1h]) == 0  OR absent(increase(executor_bid_total{scenario="Won"}[1h])) == 1
      for: 30m
      labels:
        severity: error
