[package]
edition = "2021"
license = "Apache-2.0"
name    = "portal-precompile"
version = "1.5.0-rc.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3", default-features = false }

sp-std = { git = "https://github.com/paritytech/polkadot-sdk.git", tag = "polkadot-parachains-v1.2.0", default-features = false }

frame-support = { git = "https://github.com/paritytech/polkadot-sdk.git", default-features = false, tag = "polkadot-parachains-v1.2.0" }
frame-system  = { git = "https://github.com/paritytech/polkadot-sdk.git", default-features = false, tag = "polkadot-parachains-v1.2.0" }

fp-evm        = { path = "../../primitives", default-features = false }
pallet-evm    = { path = "../..", default-features = false }
pallet-portal = { path = "../../../portal", default-features = false }

t3rn-primitives = { default-features = false, path = "../../../../primitives" }

[dev-dependencies]
pallet-evm             = { path = "../.." }
rlp                    = { version = "0.5" }
t3rn-mini-mock-runtime = { path = "../../../../runtime/mini-mock" }

[features]
default = [ "std" ]
std     = [ "pallet-portal/std", "sp-std/std", "codec/std", "t3rn-primitives/std", "frame-support/std", "frame-system/std", "fp-evm/std", "pallet-evm/std" ]
