jobs:
  - name: send-sfx-transfer
    env:
      - name: CIRCUIT_WS_ENDPOINT
        value: wss://rpc.t0rn.io
      - name: RPC_CIRCUIT_ENDPOINT
        value: https://rpc.t0rn.io
      - name: LOG_LEVEL
        value: debug
      # SFX CONFIG
      - name: SFX_TRAN_TO
        value: 5F3vTGGG56DetArfvmtZseV6fEZeCQpdYgijzzsQdBqdxmen
      - name: SFX_TRAN_INSURANCE
        value: "1"
      - name: SFX_TRAN_AMOUNT
        value: "0.01"
      
    schedule: "*/30 * * * *"
    args:
    - submit
    - -s
    - transfer.json
    activeDeadlineSeconds: 300