[package]
name = "ethash"
description = "An Apache-licensed Ethash implementation."
version = "0.5.0"
authors = ["Wei Tang <hi@that.world>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
ethereum-types = { version = "0.12.1", default-features = false }
#ethereum-types = { path = "../../../../../vendor/parity-common/ethereum-types", default-features = false, features = ["codec", "rlp", "serialize"] }
rlp = { version = "0.5", default-features = false }
byteorder = { version = "1", default-features = false }
sha3 = { version = "0.8", default-features = false }

[dev-dependencies]
hex-literal = "0.2.1"

[features]
default = ["std"]
std = [
  "ethereum-types/std",
  "rlp/std",
  "byteorder/std",
  "sha3/std",
]
