[package]
authors     = [ "Wei Tang <hi@that.world>" ]
description = "An Apache-licensed Ethash implementation."
edition     = "2018"
license     = "Apache-2.0"
name        = "ethash"
version     = "0.5.0"

[dependencies]
ethereum-types = { version = "0.12.1", default-features = false }
#ethereum-types = { path = "../../../../../vendor/parity-common/ethereum-types", default-features = false, features = ["codec", "rlp", "serialize"] }
byteorder = { version = "1", default-features = false }
rlp       = { version = "0.5", default-features = false }
sha3      = { version = "0.8", default-features = false }

[dev-dependencies]
hex-literal = "0.2.1"

[features]
default = [ "std" ]
std     = [ "ethereum-types/std", "rlp/std", "byteorder/std", "sha3/std" ]
