[package]
authors     = { workspace = true }
build       = "build.rs"
description = "t7rn Parachain node - t3rn's collator to Kusama"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "t7rn-parachain-collator"
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[[bin]]
name = "t7rn-collator"
path = "src/main.rs"

[dependencies]
# Extras
clap = { version = "4.0.32", features = ["derive"] }
log = "0.4.17"
codec = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server"] }
hex-literal            = "0.4"
futures = "0.3.28"
color-print = "0.3.4"

sc-cli                  = { workspace = true }
sc-client-api           = { workspace = true }
sc-consensus            = { workspace = true }
sc-consensus-aura       = { workspace = true }
sc-executor             = { workspace = true }
sc-consensus-grandpa    = { workspace = true }
sc-keystore             = { workspace = true }
sp-keystore             = { workspace = true }
sc-network              = { workspace = true }
sc-network-sync         = { workspace = true }
sc-service              = { workspace = true }
sc-telemetry            = { workspace = true }
sc-transaction-pool     = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-consensus            = { workspace = true }
sp-consensus-aura       = { workspace = true }
sp-core                 = { workspace = true }
sp-consensus-grandpa    = { workspace = true }
sp-inherents            = { workspace = true }
sp-keyring              = { workspace = true }
sp-runtime              = { workspace = true }
sp-timestamp            = { workspace = true }

sc-sysinfo                     = { workspace = true }
sc-tracing                     = { workspace = true }
sc-network-common              = { workspace = true }
substrate-prometheus-endpoint  = { workspace = true }

# These dependencies are used for the node template's RPCs

pallet-asset-tx-payment        = { workspace = true }
pallet-transaction-payment-rpc = { workspace = true }
sc-basic-authorship            = { workspace = true }
sc-rpc                         = { workspace = true }
sc-rpc-api                     = { workspace = true }
sp-api                         = { workspace = true }
sp-block-builder               = { workspace = true }
sp-blockchain                  = { workspace = true }
substrate-frame-rpc-system     = { workspace = true }

# These dependencies are used for runtime benchmarking
frame-benchmarking     = { workspace = true }
frame-benchmarking-cli = { workspace = true }
frame-system           = { workspace = true }

# Local Dependencies
parachain-runtime          = { path = "../../runtime/t7rn-parachain", package = "t7rn-parachain-runtime" }
circuit-runtime-types      = { path = "../../runtime/common-types", default-features = false }
pallet-portal-rpc          = { path = "../../pallets/portal/rpc" }
pallet-xdns                = { path = "../../pallets/xdns" }
pallet-xdns-rpc            = { path = "../../pallets/xdns/rpc" }
t3rn-abi                   = { path = "../../types/abi" }
t3rn-primitives            = { path = "../../primitives" }
t3rn-types                 = { path = "../../types" }

sc-chain-spec                  = { workspace = true }
sc-offchain                    = { workspace = true }

# Polkadot
polkadot-cli        = { workspace = true }
polkadot-parachain  = { workspace = true }
polkadot-primitives = { workspace = true }
polkadot-service    = { workspace = true }

# Cumulus
cumulus-client-cli                      = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-client-collator                 = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-client-consensus-aura           = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-client-consensus-common         = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-client-network                  = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-client-service                  = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-primitives-core                 = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-primitives-parachain-inherent   = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-relay-chain-inprocess-interface = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-relay-chain-interface           = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
cumulus-relay-chain-rpc-interface       = { git = 'https://github.com/paritytech/cumulus', branch = 'polkadot-v1.0.0' }
xcm                                     = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0" }
