[package]
authors     = [ "Parity Technologies <admin@parity.io>" ]
description = "Node-specific RPC methods for interaction with contracts."
edition     = "2021"
homepage    = "https://substrate.io"
license     = "Apache-2.0"
name        = "pallet-contracts-rpc"
readme      = "README.md"
repository  = "https://github.com/paritytech/substrate/"
version     = "4.0.0-dev"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
codec               = { package = "parity-scale-codec", version = "3" }
jsonrpc-core        = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-derive      = "18.0.0"
jsonrpsee           = { version = "0.18.2", features = [ "server", "macros" ] }
serde               = { version = "1", features = [ "derive" ] }

# Substrate Dependencies
pallet-contracts-primitives      = { version = "5.0.0", path = "../primitives" }
pallet-contracts-rpc-runtime-api = { version = "4.0.0-dev", path = "runtime-api" }
sp-api                           = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-blockchain                    = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-core                          = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-rpc                           = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }
sp-runtime                       = { git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', default-features = false }

[dev-dependencies]
serde_json = "1"
