[package]
name = "versatile-wasm"
version = "0.1.0"
authors = ["Maciej Baj <maciej@maciejbaj.com>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://t3rn.io"
repository = "https://github.com/t3rn/t3rn/"
description = "A crate that hosts a common definitions that are relevant for the escrow-gateway."

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
bitflags = "1.0"
# This crate should not rely on any of the frame primitives.
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }
parity-wasm = { version = "0.41.0", default-features = false }
pwasm-utils = { version = "0.14.0", default-features = false }
wasmi-validation = { version = "0.3.0", default-features = false }
transaction-payment = { package = "pallet-transaction-payment", version = "2.0.0", default-features = false }
wat = { version = "1.0", optional = true, default-features = false }
gateway-escrow-engine = { package = "gateway-escrow-engine", version = '2.0.0', path = '..', default-features = false}

[dependencies.frame-support]
default-features = false
version = '2.0.0'

[dependencies.system]
default-features = false
version = '2.0.0'
package = 'frame-system'

[dependencies.contracts]
default-features = false
package = 'pallet-contracts'
version = '2.0.0'

[dependencies.sudo]
default-features = false
package = 'pallet-sudo'
version = '2.0.0'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0'

[dependencies.sp-std]
default-features = false
version = '2.0.0'

[dependencies.sp-sandbox]
default-features = false
version = '0.8.0'

[dependencies.primitive-types]
default-features = false
features = ['codec']
version = "0.7.0"

[dev-dependencies.substrate-test-runtime]
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0'
version = '2.0.0'

[features]
default = ["std"]
std = [
	'codec/std',
	'transaction-payment/std',
	'frame-support/std',
	'primitive-types/std',
	'contracts/std',
	'system/std',
	'sudo/std',
	'sp-std/std',
	'sp-sandbox/std'
]
