[package]
name = "jsonrpc-runtime-client"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
futures = "0.1.29"
hyper = "~0.12.35"
jsonrpc-core-client = { version = "15.1.0", features = ["http"] }
jsonrpsee-types = "0.2.0"
log = "0.4.8"
env_logger = "0.8.2"

node-primitives = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sp-tracing = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8"}
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8"}
frame-metadata = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.8"}

async-std = { version = "1.6.5", features = ["attributes", "tokio1"] }
async-trait = "0.1.40"
codec = { package = "parity-scale-codec", version = "2.0.0" }
num-traits = "0.2"

tokio = "1.8.0"
bp-polkadot-core = { path = "../../../../vendor/bridges/primitives/polkadot-core" }
relay-substrate-client = { version = "0.1.0", path = "../../../../vendor/bridges/relays/client-substrate" }
