{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $app_version := .Chart.AppVersion | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $repository := .Values.repository }}
{{- $tag := .Values.tag }}
{{- $pod_annotations := .Values.podAnnotations }}
{{- $podSecurityContext := .Values.podSecurityContext }}
{{- $resources := .Values.resources }}
{{- $nodeSelector := .Values.nodeSelector }}
{{- $affinity := .Values.affinity }}
{{- $tolerations := .Values.tolerations }}


{{- range $profile := .Values.rangers }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $release_name }}-{{ $profile }}
  labels:
    helm.sh/chart: {{ $release_name }}-{{ $chart_version }}
    app.kubernetes.io/name: {{ $release_name }}-{{ $profile }}
    app.kubernetes.io/instance: {{ $release_name }}-{{ $profile }}
    app.kubernetes.io/version: {{ $app_version }}
    app.kubernetes.io/managed-by: Helm      
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $release_name }}-{{ $profile }}
      app.kubernetes.io/instance: {{ $release_name }}-{{ $profile }}
  template:
    metadata:
      {{- with $pod_annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ $release_name }}-{{ $profile }}
        app.kubernetes.io/instance: {{ $release_name }}-{{ $profile }}
    spec:
      serviceAccountName: {{ $release_name }}-{{ $profile }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $release_name }}
          image: "{{ $repository }}:{{ $tag }}"
          resources:
            {{- toYaml $resources | nindent 12 }}
          env:
            - name: LOG_LEVEL
              value: "{{ $profile == "polkadot" | ternary "debug", "info" }}"
            - name: PROFILE
              value: "{{ $profile }}"
            - name: CIRCUIT_SIGNER_KEY
              valueFrom:
                secretKeyRef:
                  name: grandpa-ranger
                  key: {{ $profile }}
          resources:
            {{- toYaml $resources | nindent 12 }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}