{{- $chart_name := .Chart.Name }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- $app_version := .Chart.AppVersion | replace "+" "_" }}
{{- $release_name := .Release.Name }}
{{- $repository := .Values.repository }}
{{- $tag := .Values.tag }}

{{- range $profile := .Values.rangers }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $release_name }}-{{ $profile }}
  labels:
    helm.sh/chart: {{ $release_name }}-{{ $chart_version }}
    app.kubernetes.io/name: {{ $release_name }}-{{ $profile }}
    app.kubernetes.io/instance: {{ $release_name }}-{{ $profile }}
    app.kubernetes.io/version: {{ $app_version }}
    app.kubernetes.io/managed-by: Helm
{{- end }}