[package]
authors     = [ "Parity Technologies <admin@parity.io>" ]
description = "A crate that hosts a common definitions that are relevant for the pallet-contracts."
edition     = { workspace = true }
homepage    = "https://substrate.io"
license     = { workspace = true }
name        = "pallet-contracts-primitives"
readme      = { workspace = true }
repository  = "https://github.com/paritytech/substrate/"
version     = "5.0.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
bitflags   = { workspace = true }
codec      = { workspace = true, package = "parity-scale-codec" }
scale-info = { workspace = true }
serde      = { workspace = true, optional = true }

# Substrate Dependencies (This crate should not rely on frame)
sp-core    = { workspace = true }
sp-rpc     = { workspace = true, optional = true }
sp-runtime = { workspace = true }
sp-std     = { workspace = true }
sp-weights = { workspace = true }

[features]
default = [ "std" ]
std     = [ "codec/std", "scale-info/std", "sp-core/std", "sp-runtime/std", "sp-std/std", "sp-rpc", "serde" ]
