[package]
authors     = [ "Parity Technologies <admin@parity.io>" ]
description = "A crate that hosts a common definitions that are relevant for the pallet-contracts."
edition     = { workspace = true }
homepage    = "https://substrate.io"
license     = { workspace = true }
name        = "pallet-contracts-primitives"
readme      = { workspace = true }
repository  = "https://github.com/paritytech/substrate/"
version     = "5.0.0"

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[dependencies]
bitflags   = "1.0"
codec      = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [ "derive" ] }
scale-info = { version = "2.0.0", default-features = false, features = [ "derive" ] }
serde      = { version = "1.0", features = [ "derive" ], optional = true }

# Substrate Dependencies (This crate should not rely on frame)
sp-core    = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-rpc     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27', optional = true }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }
sp-std     = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v0.9.27' }

[features]
default = [ "std" ]
std     = [ "codec/std", "scale-info/std", "sp-core/std", "sp-runtime/std", "sp-std/std", "sp-rpc", "serde" ]
