[package]
authors     = [ "t3rn ltd. <team@t3rn.io>" ]
description = "A crate that with t3rn ABI cross-codec, SCALE, RLP, and more"
edition     = "2021"
homepage    = "https://t3rn.io"
license     = "Apache-2.0"
name        = "t3rn-mini-mock-runtime"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.5.0-rc.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes      = { version = "1.2.1" }
codec      = { package = "parity-scale-codec", version = "3", features = [ "derive" ] }
num        = { version = "0.4.0" }
num-traits = { version = "0.2" }
scale-info = { version = "2.1.1", features = [ "derive" ] }
serde      = { version = "1.0", features = [ "derive" ] }

sp-core    = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-io      = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-std     = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

frame-support     = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
frame-system      = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
pallet-aura       = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

pallet-insecure-randomness-collective-flip = { package = "pallet-randomness-collective-flip", git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

rlp = { version = "0.5.2", features = [ "derive" ] }

ethabi      = "18.0.0"
hex         = "0.4"
hex-literal = "0.3.1"
rlp-derive  = "0.1.0"
serde_json  = "1.0.41"

t3rn-abi        = { path = "../../types/abi" }
t3rn-primitives = { path = "../../primitives" }

# for mini-mock events
pallet-assets    = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
pallet-balances  = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
pallet-contracts = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

# for mini-mock runtime
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
pallet-treasury  = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.27" }

# t3rn pallets
pallet-account-manager           = { path = "../../pallets/account-manager" }
pallet-attesters                 = { path = "../../pallets/attesters" }
pallet-circuit                   = { path = "../../pallets/circuit", features = ["test-skip-verification"] }
pallet-circuit-vacuum            = { path = "../../pallets/circuit/vacuum" }
pallet-clock                     = { path = "../../pallets/clock" }
pallet-grandpa-finality-verifier = { path = "../../finality-verifiers/grandpa" }
pallet-portal                    = { path = "../../pallets/portal" }
pallet-rewards                   = { path = "../../pallets/rewards" }
pallet-xdns                      = { path = "../../pallets/xdns" }
pallet-eth2-finality-verifier    = { git = "https://github.com/t3rn/eth2-light-client", tag = "v0.0.6" }

circuit-runtime-types = { path = "../../runtime/common-types" }
