[package]
authors     = { workspace = true }
description = "Circuit standalone t2rn runtime"
edition     = { workspace = true }
homepage    = { workspace = true }
license     = { workspace = true }
name        = "t2rn-parachain-runtime"
repository  = { workspace = true }
version     = { workspace = true }

[package.metadata.docs.rs]
targets = [ "x86_64-unknown-linux-gnu" ]

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", optional = true  }

[dependencies]
codec       = { package = "parity-scale-codec", version = "3", default-features = false, features = [ "derive" ] }
hex-literal = { version = "0.3", optional = true }
log         = { version = "0.4", default-features = false }
num-traits  = { version = "0.2", default-features = false }
scale-info  = { version = "2.9.0", default-features = false, features = [ "derive" ] }
serde       = { version = "1.0", default-features = false, optional = true, features = [ "derive" ] }

polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v1.0.0" }

# Circuit dependencies
pallet-account-manager                    = { path = "../../pallets/account-manager", default-features = false }
pallet-attesters                          = { path = "../../pallets/attesters", default-features = false }
pallet-circuit                            = { path = "../../pallets/circuit", default-features = false }
pallet-vacuum                             = { path = "../../pallets/circuit/vacuum", package = "pallet-circuit-vacuum", default-features = false }
pallet-clock                              = { path = "../../pallets/clock", default-features = false }
pallet-contracts-registry                 = { path = "../../pallets/contracts-registry", default-features = false }
#pallet-contracts-registry-rpc-runtime-api = { path = "../../pallets/contracts-registry/rpc/runtime-api", default-features = false }
pallet-eth2-finality-verifier             = { git = "https://github.com/t3rn/eth2-light-client", tag = "eth-v1.1.4", default-features = false }
pallet-sepolia-finality-verifier          = { git = "https://github.com/t3rn/eth2-light-client", tag = "sepolia-v1.1.10", default-features = false }
pallet-grandpa-finality-verifier          = { path = "../../finality-verifiers/grandpa", default-features = false }
pallet-portal                             = { path = "../../pallets/portal", default-features = false }
pallet-portal-rpc-runtime-api             = { path = "../../pallets/portal/rpc/runtime-api", default-features = false }
pallet-rewards                            = { path = "../../pallets/rewards", default-features = false }
pallet-xdns                               = { path = "../../pallets/xdns", default-features = false }
pallet-xdns-rpc-runtime-api               = { path = "../../pallets/xdns/rpc/runtime-api", default-features = false }
t3rn-abi                                  = { path = "../../types/abi", default-features = false }
t3rn-primitives                           = { default-features = false, path = "../../primitives" }
t3rn-types                                = { path = "../../types", default-features = false }

# Smart contracts VMs
#evm-precompile-util                  = { default-features = false, path = "../../pallets/evm/precompile/util", package = "precompile-util" }
pallet-3vm                           = { default-features = false, path = "../../pallets/3vm" }
pallet-3vm-contracts                 = { default-features = false, path = "../../pallets/contracts", package = "pallet-contracts" }
pallet-3vm-contracts-primitives      = { default-features = false, path = "../../pallets/contracts/primitives", package = "pallet-contracts-primitives" }
#pallet-3vm-contracts-rpc-runtime-api = { default-features = false, path = "../../pallets/contracts/rpc/runtime-api", package = "pallet-contracts-rpc-runtime-api" }
pallet-3vm-evm                       = { default-features = false, path = "../../pallets/evm", package = "pallet-evm" }
pallet-3vm-evm-primitives            = { default-features = false, path = "../../pallets/evm/primitives", package = "fp-evm" }
#pallet-evm-rpc-runtime-api           = { default-features = false, path = "../../pallets/evm/rpc/runtime-api" }

# Substrate Dependencies
frame-executive                            = { workspace = true }
frame-support                              = { workspace = true }
frame-system                               = { workspace = true }
frame-system-rpc-runtime-api               = { workspace = true }
node-primitives                            = { workspace = true }
pallet-asset-tx-payment                    = { workspace = true }
pallet-assets                              = { workspace = true }
pallet-aura                                = { workspace = true }
pallet-authorship                          = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v1.0.0", default-features = false }
pallet-balances                            = { workspace = true }
pallet-grandpa                             = { workspace = true }
pallet-identity                            = { workspace = true }
pallet-randomness-collective-flip          = { workspace = true, package = "pallet-insecure-randomness-collective-flip" }
pallet-sudo                                = { workspace = true }
pallet-timestamp                           = { workspace = true }
pallet-transaction-payment                 = { workspace = true }
pallet-transaction-payment-rpc-runtime-api = { workspace = true }
pallet-treasury                            = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.0.0" }
pallet-utility                             = { workspace = true }

sp-api              = { workspace = true }
sp-block-builder    = { workspace = true }
sp-consensus-aura   = { workspace = true }
sp-core             = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-inherents        = { workspace = true }
sp-io               = { workspace = true }
sp-offchain         = { workspace = true }
sp-runtime          = { workspace = true }
sp-session          = { workspace = true }
sp-std              = { workspace = true }
sp-transaction-pool = { workspace = true }
sp-trie             = { workspace = true }
sp-version          = { workspace = true }

# Benchmarking
frame-benchmarking        = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0', optional = true }
frame-system-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate", branch = 'polkadot-v1.0.0', optional = true }

# Common
# circuit-runtime-pallets = { path = "../common-pallets", default-features = false  }
circuit-runtime-types = { path = "../common-types", default-features = false }

pallet-maintenance-mode                   = { path = "../../pallets/maintenance-mode", default-features = false }

[features]
default = [ "std", "contracts-unstable-interface" ]
std = [
  "codec/std",
  "frame-executive/std",
  "frame-support/std",
  "frame-system-rpc-runtime-api/std",
  "frame-system/std",
  "log/std",
  "scale-info/std",
  "pallet-aura/std",
  "pallet-authorship/std",
  "pallet-assets/std",
  "pallet-attesters/std",
  "pallet-rewards/std",
  "pallet-asset-tx-payment/std",
  "t3rn-primitives/std",
  "t3rn-types/std",
  "t3rn-abi/std",
  "num-traits/std",
  "pallet-xdns/std",
  "pallet-xdns-rpc-runtime-api/std",
#  "pallet-contracts-registry-rpc-runtime-api/std",
  "pallet-circuit/std",
  "pallet-vacuum/std",
  "pallet-portal/std",
  "pallet-portal-rpc-runtime-api/std",
  "pallet-grandpa-finality-verifier/std",
  "pallet-3vm/std",
  "pallet-3vm-contracts/std",
  # "circuit-runtime-pallets/std",
  "pallet-eth2-finality-verifier/std",
  "pallet-sepolia-finality-verifier/std",
  "pallet-3vm-contracts-primitives/std",
#  "pallet-3vm-contracts-rpc-runtime-api/std",
  "pallet-3vm-evm/std",
  "pallet-3vm-evm-primitives/std",
#  "pallet-evm-rpc-runtime-api/std",
#  "evm-precompile-util/std",
  "pallet-account-manager/std",
  "pallet-contracts-registry/std",
  "pallet-balances/std",
  "pallet-treasury/std",
  "pallet-grandpa/std",
  "pallet-randomness-collective-flip/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-transaction-payment/std",
  "serde/std",
  "sp-io/std",
  "sp-api/std",
  "sp-block-builder/std",
  "sp-consensus-aura/std",
  "sp-core/std",
  "sp-consensus-grandpa/std",
  "polkadot-runtime-common/std",
  "sp-inherents/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-trie/std",
  "sp-version/std",
  "node-primitives/std",
  "pallet-utility/std",
  "pallet-identity/std",
  "pallet-clock/std",
  "circuit-runtime-types/std",
  "pallet-maintenance-mode/std",
  "substrate-wasm-builder",
]

# TODO: https://github.com/paritytech/parity-bridges-common/issues/390
# I've left the feature flag here to test our CI configuration
runtime-benchmarks = [
  'frame-benchmarking/runtime-benchmarks',
  'frame-support/runtime-benchmarks',
  'frame-system-benchmarking',
  'frame-system/runtime-benchmarks',
  'hex-literal',
  'pallet-account-manager/runtime-benchmarks',
  "pallet-assets/runtime-benchmarks",
  'pallet-balances/runtime-benchmarks',
  'pallet-contracts-registry/runtime-benchmarks',
  'pallet-xdns/runtime-benchmarks',
  'pallet-attesters/runtime-benchmarks',
  'pallet-rewards/runtime-benchmarks',
  'pallet-timestamp/runtime-benchmarks',
  'sp-runtime/runtime-benchmarks',
  "pallet-treasury/runtime-benchmarks",
  "pallet-3vm/runtime-benchmarks",
  "pallet-circuit/runtime-benchmarks",
  "pallet-vacuum/runtime-benchmarks",
  "pallet-clock/runtime-benchmarks",
  "pallet-3vm-contracts/runtime-benchmarks",
  "pallet-3vm-evm/runtime-benchmarks",
  "pallet-grandpa/runtime-benchmarks",
  "pallet-grandpa-finality-verifier/runtime-benchmarks",
  "pallet-eth2-finality-verifier/runtime-benchmarks",
  "pallet-sepolia-finality-verifier/runtime-benchmarks",
  "pallet-identity/runtime-benchmarks",
  "pallet-utility/runtime-benchmarks",
  "pallet-sudo/runtime-benchmarks",
  "polkadot-runtime-common/runtime-benchmarks",
  "pallet-asset-tx-payment/runtime-benchmarks",
]
# Make contract callable functions marked as __unstable__ available. Do not enable
# on live chains as those are subject to change.
contracts-unstable-interface = [ "pallet-3vm-contracts/unstable-interface" ]
