[package]
name        = "pallet-attesters"
edition     = "2018"
homepage    = "https://t3rn.io"
license     = "Apache-2.0"
readme      = "README.md"
repository  = "https://github.com/t3rn/t3rn/"
version     = "1.9.0-rc.0"

[dependencies]
frame-support      = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
frame-system      = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

scale-info       = { version = "2.1.1", default-features = false, features = [ "derive" ] }
serde            = { version = "1.0", default-features = false, optional = true, features = [ "derive" ] }

codec            = { package = "parity-scale-codec", version = "3", default-features = false }
log              = { version = "0.4", default-features = false }

sp-core            = { git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27', default-features = false }
sp-io              = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-runtime         = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }
sp-std             = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27' }

frame-benchmarking = { default-features = false, git = "https://github.com/paritytech/substrate.git", branch = 'polkadot-v0.9.27', optional = true }

[dev-dependencies]
hex                             = "0.4.2"
hex-literal                     = "0.2.1"

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "sp-core/std",
    "sp-std/std",
    "frame-support/std",
    "frame-system/std",
    "sp-io/std",
]

try-runtime = [ "frame-support/try-runtime", "frame-system/try-runtime" ]

runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks"
]