[package]
authors = ['Maciej Baj <https://github.com/MaciejBaj>']
description = 'Gateway for multi-phase contracts execution secured by escrow accounts'
edition = '2018'
homepage = 'https://github.com/t3rn/t3rn'
license = 'Apache 2.0'
name = 'pallet-contracts-gateway'
repository = 'https://github.com/t3rn/t3rn.git'
version = '0.3.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.reduce]
version = "0.1"

[dependencies.gateway-escrow-engine]
default-features = false
path = "../../escrow-engine"
version = '0.3.0'
#branch = 'master'
#git = 'https://github.com/t3rn/gateway-pallet.git'
#version = '2.0.0'

[dependencies.frame-support]
default-features = false
version = '2.0.0'

[dependencies.frame-system]
default-features = false
version = '2.0.0'

[dependencies.sudo]
default-features = false
package = 'pallet-sudo'
version = '2.0.0'

[dependencies.pallet-balances]
default-features = false
version = '2.0.0'

[dependencies.escrow-contracts-wrapper]
default-features = false
#git = 'https://github.com/MaciejBaj/pallet-contracts.git'
#branch = 'escrow-contracts-m3'
path = "../../escrow-engine/escrow-contracts-wrapper"
version = '0.3.0'

[dependencies.sp-std]
default-features = false
version = '2.0.0'

[dev-dependencies.sp-core]
default-features = false
version = '2.0.0'

[dev-dependencies.sp-io]
default-features = false
version = '2.0.0'

[dependencies.sp-runtime]
default-features = false
version = '2.0.0'

[dev-dependencies.pallet-timestamp]
version = '2.0.0'

[dev-dependencies.contracts]
package = "pallet-contracts"
default-features = false
version = '2.0.0'

[dev-dependencies.pallet-randomness-collective-flip]
default-features = false
version = '2.0.0'

[dev-dependencies.anyhow]
version = '*'

[dev-dependencies]
wat = { version = "1.0", default-features = false }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'pallet-balances/std',
    'frame-system/std',
    'escrow-contracts-wrapper/std',
    'gateway-escrow-engine/std',
]
