name: Automatic

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [closed, ready_for_review, assigned, review_requested, auto_merge_enabled]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  summary:
    name: PR Summary
    runs-on: self-hosted
    steps:
      - uses: fluxninja/openai-pr-reviewer@1.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          disable_review: true
          review_simple_changes: false
          review_comment_lgtm: false
