name: Circuit CI

on:
  push:
  pull_request:
    branches:
      - development
    paths:
      - circuit/**/*.rs
      - circuit/**/*.toml
      - circuit/**/*.lock
      - .github/workflows/circuit_ci.yml

env:
  RUST_BACKTRACE: 1

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - name: ğŸ¦€ install stable
        uses: hecrj/setup-rust-action@v1.3.4

      - name: ğŸŒ˜ install nightly and its wasm target
        run: |
          rustup toolchain install nightly-2021-04-05 --profile minimal
          rustup target add wasm32-unknown-unknown --toolchain nightly-2021-04-05

      - name: ğŸŒŒ circuit
        run: cd ./circuit

      - name: ğŸ­ build
        run: cargo build

      - name: ğŸ™ˆ monkey test
        run: ./target/debug/circuit --version

      - name: ğŸ“¼ build unit tests
        run: cargo test --locked --workspace --no-run

      - name: ğŸ¥ run unit tests
        run: cargo test --locked --workspace