name: Circuit Collation Check

on:
  schedule:
    - cron: '33 3 * * *'

env:
  COLLATOR_IMAGE: circuit-collator:update_v0.9.19

jobs:
  collate-check:
    runs-on: self-hosted
    steps:
      - name: â˜ Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: development
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: ðŸ‹ Rebuild fresh Circuit image
        working-directory: ./docker/devnet
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker image rm -f ${{ env.COLLATOR_IMAGE }}
          docker build -t ${{ env.COLLATOR_IMAGE }} -f t3rn.Dockerfile ../..

      - name: Up âš¡BI devnet
        working-directory: ./docker/devnet
        run: ./run.sh devnet

      - name: ðŸ§± Check Circuit's collations
        run: |
          finalized_head(){
            printf $( \
              curl \
                -sSfH "content-type: application/json" \
                -d '{"id":1,"jsonrpc":"2.0","method":"chain_getFinalizedHead","params":[]}' \
                http://localhost:8833 \
                | \
                jq -r .result \
            )
          }
          start_hash=$(finalized_head)
          block_hash=$start_hash
          i=$((0))
          echo "start_hash $start_hash"
          while [[ $block_hash -eq $start_hash ]]; do
            sleep 6s
            block_hash=$(finalized_head)
            echo "$i block_hash $block_hash"
            i=$((i+1))
            if (( $i == 34 )); then
              echo "circuit not producing collations" >&2
              exit 1
            fi
          done