# This workflow is triggered by Dependabot PRs and updates the Cargo.lock file
name: Dependabot

on:
  pull_request:
    types: [opened]
  
permissions:
  contents: read
  pull-requests: write

jobs:
  update-cargo-lock:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }} # checkout the branch of the PR because pull_request_target is on the base branch
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.T3RN_CI_GPG_PRIVATE_KEY }}

      - name: Check if commit was made by Dependabot
        run: |
          author="${{ github.event.pull_request.user.login }}"

          # ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}"
          echo "is dependabot: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}"

          if [ "${author}" = "dependabot[bot]" ]; then
            echo "Commit was made by Dependabot"
            echo "DEPENDABOT=true" >> $GITHUB_ENV
          else
            echo "Commit was not made by Dependabot"
            echo "DEPENDABOT=false" >> $GITHUB_ENV
          fi

      - name: âš™ Install rust toolchain defined in rust-toolchain.toml
        if: ${{ env.DEPENDABOT == 'true' }}
        run: rustup show

      - name: Update Cargo.lock
        if: ${{ env.DEPENDABOT == 'true' }}
        run: |
          cargo metadata > /dev/null # output is too long for github actions
          if [[ -n $(git status --porcelain) ]]; then
            echo "GIT_DIRTY=true" >> $GITHUB_ENV
          else
            echo "GIT_DIRTY=false" >> $GITHUB_ENV
          fi

      - name: Commit Cargo.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ env.GIT_DIRTY == 'true' && env.DEPENDABOT == 'true' }}
        with:
          commit_message: "build(lock): update Cargo.lock"
          file_pattern: Cargo.lock
          commit_user_name: t3rn-ci
          commit_user_email: 89840377+t3rn-ci@users.noreply.github.com

      - name: Comment on changes
        if: ${{ env.GIT_DIRTY == 'true' && env.DEPENDABOT == 'true' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            :robot: I have updated the Cargo.lock file for you.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Comment on no changes
        if: ${{ env.GIT_DIRTY == 'false' && env.DEPENDABOT == 'true' }}
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            :robot: Cargo.lock is already up to date.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

