#name: Gateway CI
#
#on:
#  pull_request:
#    paths:
#      - gateway/**/*.rs
#      - gateway/**/Cargo.toml
#      - gateway/**/Cargo.lock
#      - .github/workflows/gateway.yml
#
#env:
#  RUST_BACKTRACE: 1
#  CARGO_TERM_COLOR: always
#
#jobs:
#  format:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: â˜ï¸Checkout git repo
#        uses: actions/checkout@master
#        with:
#          submodules: recursive
#
#      - name: âš™ï¸Get nightly rust toolchain with wasm target
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly-2021-11-01
#          profile: minimal
#          components: rustfmt
#          override: true
#
#      - name: ğŸ“œ Format code
#        uses: actions-rs/cargo@v1
#        with:
#          command: fmt
#          args: |
#            -p gateway
#            -p gateway-runtime
#            -p gateway-rpc
#            --manifest-path gateway/Cargo.toml -- --check
#
#  lint:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: â˜ï¸Checkout git repo
#        uses: actions/checkout@master
#        with:
#          submodules: recursive
#
#      - name: ğŸ•’ Cache LLVM and Clang
#        id: cache-llvm
#        uses: actions/cache@v2
#        with:
#          path: |
#            ./llvm
#          key: llvm-gateway
#
#      - name: ğŸ”¨ Install LLVM and Clang
#        uses: KyleMayes/install-llvm-action@v1
#        with:
#          version: "12.0.0"
#          ubuntu-version: "20.04"
#          directory: ${{ runner.temp }}/llvm
#          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
#
#      - name: âš™ï¸Get nightly rust toolchain with wasm target
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly-2021-11-01
#          target: wasm32-unknown-unknown
#          components: clippy
#          override: true
#
#      - name: ğŸ•’ Cache Rust binaries and packages
#        uses: actions/cache@v2
#        id: cache-rust
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            gateway/target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('gateway/Cargo.lock') }}
#
#      - name: ğŸ“‘ Lint code
#        uses: actions-rs/cargo@v1
#        with:
#          command: clippy
#          args: |
#            -p gateway
#            -p gateway-runtime
#            -p gateway-rpc
#            --manifest-path gateway/Cargo.toml
#
#  check:
#    runs-on: ubuntu-20.04
#    needs: [format, lint]
#    steps:
#      - name: â˜ Checkout git repo
#        uses: actions/checkout@master
#        with:
#          submodules: recursive
#
#      - name: ğŸ•’ Cache LLVM and Clang
#        id: cache-llvm
#        uses: actions/cache@v2
#        with:
#          path: |
#            ./llvm
#          key: llvm-gateway
#
#      - name: ğŸ”¨ Install LLVM and Clang
#        uses: KyleMayes/install-llvm-action@v1
#        with:
#          version: "12.0.0"
#          ubuntu-version: "20.04"
#          directory: ${{ runner.temp }}/llvm
#          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
#
#      - name: âš™ï¸Get nightly rust toolchain with wasm target
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: nightly-2021-11-01
#          target: wasm32-unknown-unknown
#          override: true
#
#      - name: ğŸ•’ Cache Rust binaries and packages
#        uses: actions/cache@v2
#        id: cache-rust
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#            gateway/target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('gateway/Cargo.lock') }}
#
#      - name: ğŸ­ Check gateway
#        uses: actions-rs/cargo@v1
#        continue-on-error: false
#        with:
#          command: check
#          args: --locked --manifest-path gateway/Cargo.toml
