# This action assumes that version in package.json is already bumped
name: Publish @t3rn/sdk to npmjs

on:
  push:
    branches:
      - development
    paths:
      - client/packages/sdk/**
      - .github/workflows/npm-sdk.yml

jobs:
  publish:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: client/packages/sdk

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn ci
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        continue-on-error: true
