name: Semantic Version

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/release-*.yml"
      - "collator.*.Dockerfile"
      - "specs/*.raw.json"
      - ".dockerignore"

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: self-hosted
    if: ${{ !contains(github.event.pull_request.title, 'skip release') }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Calculate semantic version 
        id: version
        uses: t3rn/semantic-version@v6.0.3
        with:
          tag_prefix: "v"
          major_pattern: "/^(feat|refactor)(\\([a-z]+\\))?!:/"
          minor_pattern: "/^(feat|refactor)(\\([a-z]+\\))?:/"
          version_format: "${major}.${minor}.${patch}-rc.${increment}"
          user_format_type: "json"
          prerelease_name: "rc"

      - name: Comment Next Tag
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ### :sparkles: Next version based on commits since last release
            ##  v${{ steps.version.outputs.version }}
          message-id: semantic-version-${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
