name: Perform zombienet tests

env:
  RUST_BACKTRACE: full
  RUSTC_WRAPPER: sccache
on:
  pull_request:
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/zombienet/*/*.feature"
      - "**/zombienet/Makefile"
      - ".github/workflows/smoke-test.yml"
      - ".git/modules/*/HEAD"

jobs:
  smoke-test:
    runs-on: [self-hosted, rust]
    steps:
      - name: ‚òÅÔ∏è Checkout git repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: ‚öôÔ∏è Get nightly rust toolchain with wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-06-17
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
          override: true

      - name: Print sccache stats
        working-directory: tests/zombienet
        run: sccache --show-stats

      - name: üìº Run zombienet tests
        continue-on-error: false
        working-directory: tests/zombienet
        run: make test

      - name: Print sccache stats
        working-directory: tests/zombienet
        run: sccache --show-stats
